"use client";

import { BarChart3, CheckCircle2, Circle, FileText, FolderOpen, ListChecks, Loader2, Wrench, Clock3 } from "lucide-react";
import { useMemo, useState } from "react";
import { AgentTask, ExecutionEvent } from "@/lib/agent/types";
import { createDefaultToolRegistry } from "@/lib/agent/tools";
import { ExecutionTimeline } from "@/components/agent/execution-timeline";
import { DataPreviewTable } from "@/components/agent/data-preview-table";
import { CsvTableSummary } from "@/lib/agent/tools/file-analysis";

type PanelTab = "plan" | "tools" | "files";
type ExecutionState = { message: string; output?: string; table?: CsvTableSummary; ok: boolean } | null;

interface AgentSidePanelProps { activeTask: AgentTask | null; execution: ExecutionState; events: ExecutionEvent[]; }

export function AgentSidePanel({ activeTask, execution, events }: AgentSidePanelProps) {
  const [tab, setTab] = useState<PanelTab>("plan");
  const tools = useMemo(() => createDefaultToolRegistry().list(), []);
  const completedSteps = activeTask?.steps.filter((step) => step.status === "completed").length || 0;
  const totalSteps = activeTask?.steps.length || 0;
  const progress = totalSteps > 0 ? Math.round((completedSteps / totalSteps) * 100) : activeTask ? 5 : 0;
  return <aside className="hidden w-[340px] shrink-0 flex-col border-l border-border-main/60 bg-bg-main xl:flex" aria-label="Agent execution panel"><div className="flex items-center gap-1 border-b border-border-main/60 px-3 py-3"><PanelTabButton active={tab === "plan"} onClick={() => setTab("plan")} icon={<ListChecks className="h-4 w-4" />} label="Plan & Progress" /><PanelTabButton active={tab === "tools"} onClick={() => setTab("tools")} icon={<Wrench className="h-4 w-4" />} label="Tools" /><PanelTabButton active={tab === "files"} onClick={() => setTab("files")} icon={<FolderOpen className="h-4 w-4" />} label="Files" /></div><div className="min-h-0 flex-1 overflow-y-auto p-4 custom-scrollbar">{tab === "plan" && <PlanPanel activeTask={activeTask} progress={progress} execution={execution} events={events} />}{tab === "tools" && <ToolsPanel tools={tools} activeTask={activeTask} />}{tab === "files" && <FilesPanel activeTask={activeTask} />}</div></aside>;
}

function PanelTabButton({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) { return <button type="button" onClick={onClick} aria-pressed={active} className={`flex min-w-0 items-center gap-1.5 rounded-lg px-2 py-2 text-xs font-semibold transition-colors ${active ? "bg-sidebar-cocoa text-white" : "text-text-muted hover:bg-black/5 hover:text-text-main"}`}><span className="shrink-0">{icon}</span><span className="truncate">{label}</span></button>; }

function PlanPanel({ activeTask, progress, execution, events }: { activeTask: AgentTask | null; progress: number; execution: ExecutionState; events: ExecutionEvent[] }) { return <div className="space-y-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-text-main">Current Task</h2><span className="text-sm font-semibold text-accent">{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-accent transition-all" style={{ width: `${progress}%` }} /></div>{activeTask ? <><p className="text-sm leading-6 text-text-muted">{activeTask.goal}</p><div className="rounded-xl border border-border-main/70 bg-surface p-3"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-text-muted"><BarChart3 className="h-4 w-4 text-accent" />Step details</div><div className="space-y-3">{activeTask.steps.map((step) => <div key={step.id} className="flex items-start gap-2 text-sm"><StepIcon status={step.status} /><span className={step.status === "completed" ? "text-text-muted line-through" : "text-text-main"}>{step.title}</span></div>)}</div></div>{execution && <ExecutionOutput execution={execution} />}<div className="rounded-xl border border-border-main/70 bg-surface p-3"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-text-muted"><Clock3 className="h-4 w-4 text-accent" />Activity</div><ExecutionTimeline events={events} /></div></> : <EmptyPanel icon={<ListChecks className="h-5 w-5" />} title="No active task" description="Create a task in Agent Mode to see its plan and progress here." />}</div>; }

function ToolsPanel({ tools, activeTask }: { tools: Array<{ id: string; name: string; description: string; permission: string }>; activeTask: AgentTask | null }) { return <div className="space-y-4"><div><h2 className="text-sm font-semibold text-text-main">Tools available</h2><p className="mt-1 text-xs leading-5 text-text-muted">Only registered tools can be selected by the Agent.</p></div>{tools.map((tool) => { const step = activeTask?.steps.find((candidate) => candidate.toolId === tool.id); return <div key={tool.id} className="rounded-xl border border-border-main/70 bg-surface p-3"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-cream-highlight text-accent"><Wrench className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-text-main">{tool.name}</p><p className="text-[11px] text-text-muted">{tool.permission}</p></div>{step && <span className="text-[11px] font-semibold capitalize text-accent">{formatStepStatus(step.status)}</span>}</div><p className="mt-2 text-xs leading-5 text-text-muted">{tool.description}</p></div>; })}</div>; }

function FilesPanel({ activeTask }: { activeTask: AgentTask | null }) { return <div className="space-y-4"><div><h2 className="text-sm font-semibold text-text-main">Task files</h2><p className="mt-1 text-xs leading-5 text-text-muted">Files attached to an Agent task will appear here.</p></div>{activeTask?.attachments.length ? <div className="space-y-2">{activeTask.attachments.map((file) => <div key={file.id} className="rounded-xl border border-border-main/70 bg-surface p-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 shrink-0 text-accent" /><span className="min-w-0 truncate text-sm font-semibold text-text-main">{file.filename}</span></div><p className="mt-2 text-xs text-text-muted">{file.mediaType} · {formatBytes(file.sizeBytes)}</p></div>)}</div> : <EmptyPanel icon={<FileText className="h-5 w-5" />} title={activeTask ? "No files attached" : "No active task"} description={activeTask ? "Attach a supported file from the task composer." : "Create a task before attaching or analysing files."} />}</div>; }

function ExecutionOutput({ execution }: { execution: Exclude<ExecutionState, null> }) { return <div className={`rounded-xl border p-3 ${execution.ok ? "border-emerald-200 bg-emerald-50" : "border-red-200 bg-red-50"}`}><p className={`text-xs font-semibold ${execution.ok ? "text-emerald-800" : "text-red-700"}`}>{execution.message}</p>{execution.output && <pre className="mt-2 overflow-x-auto whitespace-pre-wrap rounded-lg bg-sidebar-cocoa px-3 py-2 text-xs text-white">{execution.output}</pre>}{execution.table && <DataPreviewTable table={execution.table} />}</div>; }

function StepIcon({ status }: { status: string }) { if (status === "completed") return <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />; if (status === "running") return <Loader2 className="mt-0.5 h-4 w-4 shrink-0 animate-spin text-accent" />; return <Circle className="mt-0.5 h-4 w-4 shrink-0 text-text-muted/50" />; }
function formatStepStatus(status: string): string { return status.replaceAll("_", " "); }
function formatBytes(size: number): string { return size < 1024 * 1024 ? `${Math.max(1, Math.round(size / 1024))} KB` : `${(size / (1024 * 1024)).toFixed(1)} MB`; }
function EmptyPanel({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <div className="rounded-xl border border-dashed border-border-main bg-surface/60 p-5 text-center"><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-xl bg-cream-highlight text-accent">{icon}</div><p className="mt-3 text-sm font-semibold text-text-main">{title}</p><p className="mt-1 text-xs leading-5 text-text-muted">{description}</p></div>; }
