"use client";

import { AlertTriangle, CheckCircle2, ShieldCheck, X } from "lucide-react";
import { AgentPlanStep, AgentTask } from "@/lib/agent/types";

interface ApprovalModalProps { task: AgentTask; step: AgentPlanStep; onApprove: () => void; onReject: () => void; }

export function ApprovalModal({ task, step, onApprove, onReject }: ApprovalModalProps) {
  return <div className="absolute inset-0 z-40 flex items-center justify-center bg-sidebar-cocoa/20 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true" aria-labelledby="approval-title"><div className="w-full max-w-md rounded-2xl border border-border-main bg-surface p-5 shadow-2xl"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-700"><ShieldCheck className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h2 id="approval-title" className="text-base font-semibold text-text-main">Approval required</h2><p className="mt-1 text-sm leading-5 text-text-muted">Susan AI needs your approval before continuing this protected step.</p></div><button type="button" onClick={onReject} aria-label="Close approval dialog" className="rounded-lg p-1.5 text-text-muted hover:bg-black/5"><X className="h-4 w-4" /></button></div><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-amber-800">Requested step</p><p className="mt-1 text-sm font-semibold text-amber-950">{step.title}</p><p className="mt-1 text-xs leading-5 text-amber-900">{step.description}</p></div><div className="mt-3 flex items-start gap-2 text-xs text-text-muted"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" /><span>This approval applies to this step only. The task goal is: <strong className="font-semibold text-text-main">{task.goal}</strong></span></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onReject} className="flex items-center gap-2 rounded-xl border border-border-main px-4 py-2.5 text-sm font-semibold text-text-main hover:bg-black/5">Reject</button><button type="button" onClick={onApprove} className="flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white hover:opacity-90"><CheckCircle2 className="h-4 w-4" />Approve & continue</button></div></div></div>;
}
