"use client";

import { CsvTableSummary } from "@/lib/agent/tools/file-analysis";

export function DataPreviewTable({ table }: { table: CsvTableSummary }) {
  return <div className="mt-3 overflow-hidden rounded-lg border border-border-main/70 bg-surface"><div className="flex items-center justify-between gap-3 border-b border-border-main/70 px-3 py-2"><p className="text-xs font-semibold text-text-main">Data preview</p><p className="text-[10px] text-text-muted">{table.rowCount} rows · {table.columns.length} columns · {table.missingValueCount} missing</p></div>{table.numericStats.length > 0 && <div className="grid gap-2 border-b border-border-main/70 p-3 sm:grid-cols-2">{table.numericStats.map((stat) => <div key={stat.column} className="rounded-lg bg-cream-highlight/60 px-2.5 py-2"><p className="truncate text-[10px] font-semibold text-accent">{stat.column}</p><div className="mt-1 grid grid-cols-3 gap-1 text-[10px] text-text-muted"><span>Avg <strong className="block text-text-main">{formatNumber(stat.average)}</strong></span><span>Min <strong className="block text-text-main">{formatNumber(stat.minimum)}</strong></span><span>Max <strong className="block text-text-main">{formatNumber(stat.maximum)}</strong></span></div></div>)}</div>}<div className="overflow-x-auto"><table className="min-w-full text-left text-[11px]"><thead className="bg-black/5 text-text-muted"><tr>{table.columns.map((column, index) => <th key={`${column}-${index}`} className="whitespace-nowrap px-3 py-2 font-semibold">{column}</th>)}</tr></thead><tbody>{table.rows.map((row, rowIndex) => <tr key={`row-${rowIndex}`} className="border-t border-border-main/50 text-text-main">{table.columns.map((column, columnIndex) => <td key={`${column}-${columnIndex}`} className="max-w-[180px] truncate px-3 py-2">{row[columnIndex] || <span className="text-text-muted/60">—</span>}</td>)}</tr>)}</tbody></table></div>{table.rowCount > table.rows.length && <p className="border-t border-border-main/70 px-3 py-2 text-[10px] text-text-muted">Showing first {table.rows.length} rows.</p>}</div>;
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value);
}
