"use client";
import { AlertTriangle, Bot, CheckCircle2, ClipboardList, Clock3, FileText, Loader2, Paperclip, Sparkles, UserRound } from "lucide-react";
import { AgentError, AgentTask, PlanStepStatus } from "@/lib/agent/types";
import { CsvTableSummary } from "@/lib/agent/tools/file-analysis";

interface InlineAgentTaskCardProps { task: AgentTask; execution: { message: string; error?: AgentError; table?: CsvTableSummary; ok: boolean } | null; }

export function InlineAgentTaskCard({ task, execution }: InlineAgentTaskCardProps) {
  const completed = task.steps.filter((step) => step.status === "completed").length;
  const current = task.steps.find((step) => step.status === "running") || task.steps.find((step) => step.status === "pending");
  const statusMessage = execution?.message || (task.status === "planning" ? "I’ll turn this goal into a safe, executable plan first." : task.status === "running" ? "I’m working through the task plan and will keep the output visible here." : task.status === "completed" ? "The task is complete and the results are ready to review." : task.status === "failed" ? "The task stopped because a step failed. You can retry or roll back safely." : "I’ve prepared a plan and am ready to execute it.");
  return <section aria-label="Agent conversation" className="mx-auto flex w-full max-w-5xl flex-col gap-3 px-4 pb-3 md:px-8">
    <div className="flex items-start justify-end gap-3"><div className="max-w-[86%] rounded-2xl rounded-tr-md bg-sidebar-cocoa px-4 py-3 text-sm leading-6 text-white shadow-sm"><p>{task.goal}</p>{task.attachments.length > 0 && <div className="mt-3 flex flex-wrap gap-2 border-t border-white/15 pt-2">{task.attachments.map((file) => <span key={file.id} className="flex items-center gap-1.5 rounded-lg bg-white/10 px-2 py-1 text-[10px] text-white/85"><Paperclip className="h-3 w-3 text-cream-highlight" />{file.filename}</span>)}</div>}</div><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-blue-100 text-blue-700"><UserRound className="h-4 w-4" /></span></div>
    <div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-sidebar-cocoa text-cream-highlight shadow-sm"><Bot className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold text-text-main">Susan AI <span className="font-normal text-text-muted">(Agent Mode)</span></h2><span className="flex items-center gap-1 rounded-full bg-cream-highlight px-2 py-0.5 text-[10px] font-semibold capitalize text-accent"><Sparkles className="h-3 w-3" />{formatStatus(task.status)}</span></div><p className="mt-1 flex items-center gap-1.5 text-xs text-text-muted"><StatusIcon status={task.status} />{statusMessage}</p><div className="mt-3 overflow-hidden rounded-2xl border border-border-main/70 bg-surface shadow-sm"><div className="flex items-start gap-3 border-b border-border-main/60 px-4 py-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-cream-highlight text-accent"><ClipboardList className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-text-main">Task Plan Created</h3><span className="text-[10px] font-medium text-text-muted">{completed}/{task.steps.length} completed</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-accent transition-all" style={{ width: `${task.steps.length ? (completed / task.steps.length) * 100 : 0}%` }} /></div></div></div><div className="divide-y divide-border-main/50">{task.steps.map((step, index) => <div key={step.id} className={`flex items-center gap-3 px-4 py-3 ${step.id === current?.id ? "bg-cream-highlight/35" : ""}`}><StepIcon status={step.status} index={index} /><div className="min-w-0 flex-1"><p className={`text-xs font-medium ${step.status === "completed" ? "text-text-muted line-through" : "text-text-main"}`}>{step.title}</p><p className="mt-0.5 truncate text-[10px] text-text-muted">{step.description}</p></div><span className={`shrink-0 text-[10px] font-semibold capitalize ${step.status === "completed" ? "text-emerald-700" : step.status === "failed" ? "text-red-700" : step.status === "running" ? "text-accent" : "text-text-muted"}`}>{formatStatus(step.status)}</span></div>)}</div>{execution?.error && <div className="flex gap-2 border-t border-red-200 bg-red-50 px-4 py-3 text-xs text-red-800"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="font-semibold">{execution.error.code}</p><p className="mt-0.5">{execution.error.recoveryHint}</p></div></div>}{execution?.ok && task.status === "completed" && <div className="flex items-center gap-2 border-t border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-medium text-emerald-800"><FileText className="h-4 w-4" />Results are ready in the Live Output workspace below.</div>}</div></div></div>
  </section>;
}
function StepIcon({ status, index }: { status: PlanStepStatus; index: number }) { if (status === "completed") return <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" />; if (status === "running") return <Loader2 className="h-4 w-4 shrink-0 animate-spin text-accent" />; if (status === "failed") return <AlertTriangle className="h-4 w-4 shrink-0 text-red-600" />; return <span className="flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-black/10 text-[9px] font-semibold text-text-muted">{index + 1}</span>; }
function StatusIcon({ status }: { status: AgentTask["status"] }) { if (status === "failed") return <AlertTriangle className="h-3.5 w-3.5 text-red-600" />; if (status === "completed") return <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />; if (status === "running") return <Loader2 className="h-3.5 w-3.5 animate-spin text-accent" />; return <Clock3 className="h-3.5 w-3.5 text-accent" />; }
function formatStatus(status: string): string { return status.replaceAll("_", " "); }
